[project]
name = "hackindia-ai-web3-builders-hackathon-2026-team-conflux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Surydevx", email = "219320689+Surydevx@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
]

[project.scripts]
hackindia-ai-web3-builders-hackathon-2026-team-conflux = "hackindia_ai_web3_builders_hackathon_2026_team_conflux:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
